package com.jcpp.droidbook.dao;

import java.util.ArrayList;
import java.util.List;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;
import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table BOOK_AUTHOR.
*/
public class BookAuthorDao extends AbstractDao<BookAuthor, Long> {

    public static final String TABLENAME = "BOOK_AUTHOR";

    /**
     * Properties of entity BookAuthor.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property BookId = new Property(1, long.class, "bookId", false, "BOOK_ID");
        public final static Property AuthorId = new Property(2, long.class, "AuthorId", false, "AUTHOR_ID");
    };

    private DaoSession daoSession;

    private Query<BookAuthor> book_BookAuthorListQuery;
    private Query<BookAuthor> author_BookAuthorListQuery;

    public BookAuthorDao(DaoConfig config) {
        super(config);
    }
    
    public BookAuthorDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'BOOK_AUTHOR' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'BOOK_ID' INTEGER NOT NULL ," + // 1: bookId
                "'AUTHOR_ID' INTEGER NOT NULL );"); // 2: AuthorId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'BOOK_AUTHOR'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, BookAuthor entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getBookId());
        stmt.bindLong(3, entity.getAuthorId());
    }

    @Override
	
    protected void attachEntity(BookAuthor entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public BookAuthor readEntity(Cursor cursor, int offset) {
        BookAuthor entity = new BookAuthor( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // bookId
            cursor.getLong(offset + 2) // AuthorId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, BookAuthor entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setBookId(cursor.getLong(offset + 1));
        entity.setAuthorId(cursor.getLong(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
	
    protected Long updateKeyAfterInsert(BookAuthor entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
	
    public Long getKey(BookAuthor entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override
	    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "bookAuthorList" to-many relationship of Book. */
    public List<BookAuthor> _queryBook_BookAuthorList(long bookId) {
        synchronized (this) {
            if (book_BookAuthorListQuery == null) {
                QueryBuilder<BookAuthor> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.BookId.eq(null));
                book_BookAuthorListQuery = queryBuilder.build();
            }
        }
        Query<BookAuthor> query = book_BookAuthorListQuery.forCurrentThread();
        query.setParameter(0, bookId);
        return query.list();
    }

    /** Internal query to resolve the "bookAuthorList" to-many relationship of Author. */
    public List<BookAuthor> _queryAuthor_BookAuthorList(long AuthorId) {
        synchronized (this) {
            if (author_BookAuthorListQuery == null) {
                QueryBuilder<BookAuthor> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.AuthorId.eq(null));
                author_BookAuthorListQuery = queryBuilder.build();
            }
        }
        Query<BookAuthor> query = author_BookAuthorListQuery.forCurrentThread();
        query.setParameter(0, AuthorId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getBookDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getAuthorDao().getAllColumns());
            builder.append(" FROM BOOK_AUTHOR T");
            builder.append(" LEFT JOIN BOOK T0 ON T.'BOOK_ID'=T0.'_id'");
            builder.append(" LEFT JOIN AUTHOR T1 ON T.'AUTHOR_ID'=T1.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected BookAuthor loadCurrentDeep(Cursor cursor, boolean lock) {
        BookAuthor entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Book book = loadCurrentOther(daoSession.getBookDao(), cursor, offset);
         if(book != null) {
            entity.setBook(book);
        }
        offset += daoSession.getBookDao().getAllColumns().length;

        Author author = loadCurrentOther(daoSession.getAuthorDao(), cursor, offset);
         if(author != null) {
            entity.setAuthor(author);
        }

        return entity;    
    }

    public BookAuthor loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<BookAuthor> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<BookAuthor> list = new ArrayList<BookAuthor>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<BookAuthor> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<BookAuthor> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
